"""Installer module for PaperNarrator.

Provides functions for:
- Checking environment variables
- Creating virtual environments
- Installing dependencies
- Downloading models
- Creating .env files
"""

import os
import sys
import subprocess
import shutil
from pathlib import Path


def check_env_var(var_name: str) -> str | None:
    """Check if environment variable exists and return its value."""
    return os.environ.get(var_name)


def prompt_for_api_key(provider_name: str) -> str:
    """Prompt user for API key."""
    print(f"\n[{provider_name} API Key]")
    print(f"Enter your {provider_name} API key (or press Enter to skip):")
    key = input(f"{provider_name} API Key: ").strip()
    return key


def create_venv(venv_path: str) -> None:
    """Create a virtual environment using uv."""
    print(f"\nCreating virtual environment at {venv_path}...")
    
    # Check if uv is available
    if shutil.which("uv") is None:
        print("Error: 'uv' is not installed. Please install it first:")
        print("  pip install uv")
        sys.exit(1)
    
    result = subprocess.run(
        ["uv", "venv", venv_path],
        check=True,
        capture_output=True,
        text=True
    )
    print(f"Virtual environment created successfully.")


def install_dependencies(venv_path: str) -> None:
    """Install dependencies using uv."""
    print("\nInstalling dependencies...")
    
    # Get activate script path based on OS
    if sys.platform == "win32":
        activate_script = os.path.join(venv_path, "Scripts", "activate.bat")
    else:
        activate_script = os.path.join(venv_path, "bin", "activate")
    
    # Install using uv pip install
    result = subprocess.run(
        ["uv", "pip", "install", "-e", "."],
        check=True,
        capture_output=True,
        text=True
    )
    print("Dependencies installed successfully.")


def create_env_file(env_path: str, config: dict) -> None:
    """Create .env file from config dictionary."""
    print(f"\nCreating .env file at {env_path}...")
    
    with open(env_path, 'w') as f:
        f.write("# PaperNarrator Configuration\n")
        f.write("# Generated by setup script\n\n")
        
        for key, value in config.items():
            if value:  # Only write non-empty values
                f.write(f"{key}={value}\n")
    
    print(f"Configuration saved to {env_path}")


def check_ollama_available() -> bool:
    """Check if Ollama is installed and running."""
    try:
        result = subprocess.run(
            ["ollama", "--version"],
            capture_output=True,
            text=True,
            timeout=5
        )
        return result.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


def download_ollama_model(model_name: str) -> None:
    """Download Ollama model."""
    print(f"\nDownloading Ollama model: {model_name}...")
    
    result = subprocess.run(
        ["ollama", "pull", model_name],
        check=True,
        capture_output=True,
        text=True
    )
    print(f"Model {model_name} downloaded successfully.")


def check_huggingface_token() -> str | None:
    """Check for HuggingFace token."""
    token = os.environ.get("HF_TOKEN") or os.environ.get("HUGGINGFACE_TOKEN")
    if token:
        return token
    
    print("\n[HuggingFace Token]")
    print("Some models may require authentication.")
    print("Enter your HuggingFace token (optional, press Enter to skip):")
    token = input("HuggingFace Token: ").strip()
    return token if token else None


def download_vibevoice_model(model_path: str = None) -> None:
    """Download VibeVoice model using Python script."""
    print("\n[Downloading VibeVoice Model]")
    print("This may take several minutes (~2GB)...")
    
    # Check if setup script exists
    if sys.platform == "win32":
        setup_script = "setup_vibevoice.bat"
    else:
        setup_script = "setup_vibevoice.sh"
    
    if os.path.exists(setup_script):
        # Run the setup script
        if sys.platform == "win32":
            subprocess.run(["cmd", "/c", "call", setup_script], check=True)
        else:
            subprocess.run(["bash", setup_script], check=True)
    else:
        print(f"Warning: {setup_script} not found. Skipping model download.")
        print("You can run it manually later with: ".rstrip())
        print(f"  {setup_script}")


def main():
    """Main installer function."""
    print("=" * 60)
    print("PaperNarrator Installer")
    print("=" * 60)
    
    # Check for uv
    if shutil.which("uv") is None:
        print("Error: 'uv' is not installed.")
        print("Please install it first: pip install uv")
        sys.exit(1)
    
    # Step 1: Check for API key
    print("\n[Configuration]")
    
    llm_provider = None
    api_key = None
    
    # Check OpenAI first
    if check_env_var("OPENAI_API_KEY"):
        llm_provider = "openai"
        api_key = check_env_var("OPENAI_API_KEY")
        print("OpenAI API key found in environment.")
    else:
        # Prompt for OpenAI key
        api_key = prompt_for_api_key("OpenAI")
        if api_key:
            llm_provider = "openai"
        else:
            # Check if user wants Ollama
            print("\nNo OpenAI API key provided.")
            if input("Would you like to use Ollama instead? (y/n): ").lower() == "y":
                llm_provider = "ollama"
                
                if not check_ollama_available():
                    print("Ollama not found. Please install Ollama first:")
                    print("  Windows: https://ollama.com/download/windows")
                    print("  macOS: brew install ollama")
                    print("  Linux: curl -fsSL https://ollama.com/install.sh | sh")
                    sys.exit(1)
                
                # Ask which model to use
                model = input("Enter Ollama model name (default: llama3.2): ").strip() or "llama3.2"
                
                # Check if model exists
                try:
                    result = subprocess.run(
                        ["ollama", "list"],
                        capture_output=True,
                        text=True
                    )
                    if model not in result.stdout:
                        print(f"Model '{model}' not found locally.")
                        if input(f"Download '{model}' from Ollama? (y/n): ").lower() == "y":
                            download_ollama_model(model)
                except Exception as e:
                    print(f"Error checking Ollama models: {e}")
    
    # Step 2: Create venv
    venv_path = ".venv"
    if os.path.exists(venv_path):
        print(f"Virtual environment already exists at {venv_path}")
        if input("Recreate it? (y/n): ").lower() != "y":
            pass  # Use existing
        else:
            shutil.rmtree(venv_path)
            create_venv(venv_path)
    else:
        create_venv(venv_path)
    
    # Step 3: Install dependencies
    install_dependencies(venv_path)
    
    # Step 4: Download VibeVoice model
    # Check for HF token first
    hf_token = check_huggingface_token()
    if hf_token:
        os.environ["HF_TOKEN"] = hf_token
    
    # Run vibevoice setup
    download_vibevoice_model()
    
    # Step 5: Create .env file
    config = {
        "LLM_PROVIDER": llm_provider,
    }
    
    if llm_provider == "openai" and api_key:
        config["OPENAI_API_KEY"] = api_key
    elif llm_provider == "ollama":
        config["OLLAMA_MODEL"] = model if 'model' in dir() else "llama3.2"
    
    if hf_token:
        config["HF_TOKEN"] = hf_token
    
    create_env_file(".env", config)
    
    # Summary
    print("\n" + "=" * 60)
    print("Installation Complete!")
    print("=" * 60)
    print(f"\nConfiguration:")
    print(f"  LLM Provider: {llm_provider}")
    if llm_provider == "ollama":
        print(f"  Model: {config.get('OLLAMA_MODEL', 'llama3.2')}")
    
    print(f"\nNext steps:")
    print(f"  1. Activate environment: {venv_path}/Scripts/activate" if sys.platform == "win32" else f"  1. Activate environment: source {venv_path}/bin/activate")
    print(f"  2. Run the app: uv run python app.py")
    print(f"  3. Open http://localhost:7860 in your browser")


if __name__ == "__main__":
    main()
